---
# This is mainly for capistrano later since sudo is no longer available in v3
- name: create sudoers file
  sudo: yes
  template: src=sudoers.j2 dest=/etc/sudoers.d/{{ user }}_webservers validate="visudo -cf %s" owner=root group=root mode=0440

- name: create application directory
  sudo: yes
  file: path=/var/www/html/{{ application }} owner={{ user }} state=directory

- name: create shared directory
  sudo: yes
  file: path={{ shared_path }} owner={{ user }} state=directory

- include: apache.yml
